#!/usr/bin/env python3
"""
Example usage of the new observations parameter in cmc-obs.

This demonstrates how to control which observations are generated,
with ERIS observations excluded by default.
"""

def example_usage():
    """
    Example showing different ways to use the observations parameter.
    
    Note: This is a demonstration of the API - actual usage would require
    a proper Snapshot object and installed dependencies.
    """
    
    print("=== CMC-OBS Observations Parameter Examples ===\n")
    
    # Example 1: Default behavior (ERIS excluded)
    print("1. Default behavior (ERIS excluded by default):")
    print("   obs.write_obs()")
    print("   → Generates: Hubble, Gaia, LOS, Number Density, Mass Function")
    print("   → Excludes: ERIS")
    print()
    
    # Example 2: Explicitly include ERIS
    print("2. Explicitly include ERIS observations:")
    print("   obs.write_obs(observations=['hubble', 'gaia', 'eris', 'los', 'nd', 'mf'])")
    print("   → Generates: All observations including ERIS")
    print()
    
    # Example 3: Only proper motion observations including ERIS
    print("3. Only proper motion observations (including ERIS):")
    print("   obs.write_obs(observations=['hubble', 'gaia', 'eris'])")
    print("   → Generates: Hubble PM, Gaia PM, ERIS PM")
    print("   → Excludes: LOS, Number Density, Mass Function")
    print()
    
    # Example 4: Only ERIS observations
    print("4. Only ERIS observations:")
    print("   obs.write_obs(observations=['eris'])")
    print("   → Generates: ERIS PM only")
    print()
    
    # Example 5: Everything except ERIS (explicit)
    print("5. Everything except ERIS (explicit):")
    print("   obs.write_obs(observations=['hubble', 'gaia', 'los', 'nd', 'mf'])")
    print("   → Generates: All observations except ERIS")
    print()
    
    # Example 6: Backwards compatibility
    print("6. Backwards compatibility:")
    print("   obs.write_obs(hubble_kwargs={}, gaia_kwargs={})")
    print("   → Works exactly as before, excludes ERIS by default")
    print()
    
    print("=== Available observation types ===")
    observation_types = {
        'hubble': 'Hubble Space Telescope proper motions',
        'gaia': 'Gaia proper motions', 
        'eris': 'ERIS proper motions',
        'los': 'Line-of-sight velocity dispersions',
        'nd': 'Number density profiles',
        'mf': 'Stellar mass functions'
    }
    
    for obs_type, description in observation_types.items():
        print(f"  '{obs_type}': {description}")
    print()


def api_reference():
    """API reference for the observations parameter"""
    
    print("=== API Reference ===\n")
    
    print("write_obs(observations=None, ...)")
    print()
    print("Parameters:")
    print("  observations : list, optional")
    print("      List of observations to generate. Valid options are:")
    print("      ['hubble', 'gaia', 'eris', 'los', 'nd', 'mf']")
    print("      Default is ['hubble', 'gaia', 'los', 'nd', 'mf'] (excludes 'eris')")
    print()
    print("Examples:")
    print("  # Default (excludes ERIS)")
    print("  obs.write_obs()")
    print()
    print("  # Include ERIS")
    print("  obs.write_obs(observations=['hubble', 'gaia', 'eris', 'los', 'nd', 'mf'])")
    print()
    print("  # Only ERIS")
    print("  obs.write_obs(observations=['eris'])")
    print()
    print("  # Only proper motions")
    print("  obs.write_obs(observations=['hubble', 'gaia', 'eris'])")
    print()


def migration_guide():
    """Migration guide for existing code"""
    
    print("=== Migration Guide ===\n")
    
    print("Existing code will continue to work without changes!")
    print()
    print("Before (still works):")
    print("  obs.write_obs(hubble_kwargs={}, gaia_kwargs={})")
    print("  → ERIS was generated by default")
    print()
    print("After this change:")
    print("  obs.write_obs(hubble_kwargs={}, gaia_kwargs={})")
    print("  → ERIS is NOT generated by default")
    print()
    print("To get ERIS observations, explicitly request them:")
    print("  obs.write_obs(")
    print("      observations=['hubble', 'gaia', 'eris', 'los', 'nd', 'mf'],")
    print("      hubble_kwargs={}, gaia_kwargs={}, eris_kwargs={}")
    print("  )")
    print()
    print("This change ensures ERIS observations are only generated when explicitly requested.")
    print()


if __name__ == "__main__":
    example_usage()
    api_reference()
    migration_guide()